// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_validation_from_receiveremail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_validation_from_receiveremail));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081505262_delete_validation_from_receiveremail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
